### ISSUE TITLE
More Plot support...

### ISSUE THREAD

**Issue by Fortifier42** [DenizenScript/Depenizen#101]
Since PlotMe is _discontinued_ it wouldn't hurt to add PlotSquared support to accompany it, if people prefer one over the other

**Comment by Morphan1** [comment]
Ehhh... On the [current Spigot page](https://www.spigotmc.org/resources/plotme-official.2131/), it says
 > PlotMe will return in Fall/Winter 2016
The plugin itself doesn't appear to be version-dependent anyway, so I say we're fine for now. If it gets to early next year and PlotMe still isn't back, then we can move to PlotSquared.

**Comment by Morphan1** [comment]
Latest update from the author:
```
Development has continued but at the moment everything is private. I won't be publishing the code publicly or creating development builds until I know everything will work. Expected release is now the end of January or early February.
```

**Comment by Noiknez** [comment]
Hi, it is early february already, can we expect PlotSquared to be supported ?

**Comment by Mwthorn** [comment]
#161
