### ISSUE TITLE
Movecraft Hook

### ISSUE THREAD

**Issue by Gregory1346** [DenizenScript/Depenizen#116]
Hey,
A movecraft hook would detect when a movecraft vehicle is destroyed, and grab the names of the player who destroyed it and the player whose ship sunk.

This could be used to broadcast stuff like 
"<shipsinker> sunk <victim>'s ship!"

Another thing I would really want as part of this would be to detect the size of the ship and give rankpoints to the player who sunk it.

So if I sunk a ship writhing a certain range, id be awarded a certain number of rankpoints. When I get to a set amount, my permissions group would change via PEX or GM.

**Comment by Morphan1** [comment]
Movecraft currently has no events for detecting things like ship destruction, or anything else for that matter. I've opened an issue here msummers123/Movecraft-3#220 - it's up to the developer now to implement it. Otherwise, there's not a whole lot we can do here.

**Comment by Gregory1346** [comment]
Thanks! Fingers crossed.

**Comment by mcmonkey4eva** [comment]
Movecraft development looks pretty dead on all forks.
Know any ones that are being updated still, @Gregory1346 ?

**Comment by Gregory1346** [comment]
Nope :(

**Comment by mcmonkey4eva** [comment]
:/
