### ISSUE TITLE
AreaShop Hook

### ISSUE THREAD

**Issue by drAkeTool** [DenizenScript/Depenizen#122]
hello, I wondered if you could give support to this great plugin
Possible flags:
```
<areashop.player.has_region> if player have region
<areashop.player.has_region[group]> if player have region in specific group
<areashop.player.regions> Player list areas
<areashop.[group].as_list> "list of areas in group"
```

events:
on areashop region [group] expires:
https://www.spigotmc.org/resources/areashop.2991/

thanks for looking at it, I hope there may be support for this

**Comment by Morphan1** [comment]
`<Morphan1> !search AreaShop`
`<monkeybot> Best matches: '!tag p@player.areashop.owned', '!tag areashop@areashop.is_bought', '!tag areashop@areashop.is_rented', '!tag areashop@areashop.groups', '!tag areashop@areashop.landlord', '!tag areashop@areashop.name', '!tag areashop@areashop.owner', '!tag areashop@areashop.worldguard_region', '!event areashop shop expires'`
