### ISSUE TITLE
Strange Socket Behavior

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#123]
First thing are these logs, my guess is that its trying to reconnect too fast.
BungeeCord logs:
http://one.denizenscript.com/haste/36758
Spigot/Bukkit Logs:
http://one.denizenscript.com/haste/36759

Also the connections between the servers are strange. I checked each server with the tag "bungee.list_servers" and they all returned DIFFERENT! Few examples are below:

KitPvP: li@server@KitPvP|server@Hub|server@CTF|server@Test|server@Skyblock|server@Kreativ1|server@Prison|server@Kreati

CTF: li@server@kitpvp|server@CTF|server@test

Hub: li@

**Comment by Morphan1** [comment]
What do your config files look like?..

**Comment by Morphan1** [comment]
Wrong button

**Comment by Mwthorn** [comment]
Config for KitPvP (Assume its about the same on all of them):
https://one.denizenscript.com/haste/36844

Config for Bungee:
https://one.denizenscript.com/haste/36845

**Comment by Morphan1** [comment]
Try the latest Depenizen build
http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/

**Comment by BlackCoyote** [comment]
I think this issue is resolved now

**Comment by Morphan1** [comment]
Yeah... Lemme know of any other  issues that do arise
