### ISSUE TITLE
Towny Allies and Enemies tags

### ISSUE THREAD

**Issue by teateatea** [DenizenScript/Depenizen#124]
Hi there!

Would it be possible to add a nation@nation.allies tag? Ideally it would return a list of the nations allies.

A nation@nation.enemies tag to match it would be great too!

There is already a nation@nation.relation[nation] tag, which could do the work if we check every nation against every other nation, but its not ideal.

Again, thank you for creating Depenizen! It's appreciated every day!
Tea

**Comment by Morphan1** [comment]
Thanks for your suggestion! It has been added to the latest build
http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/

**Comment by teateatea** [comment]
You guys are great! Thank you so much for the insanely fast turn around time!
