### ISSUE TITLE
Updated MythicMobs and MythicLibs support

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Depenizen#125]
Greeting,

There is a new official version of mythicmobs v2.5.0 out 
https://www.spigotmc.org/resources/mythicmobs.5702/

This version introduce also a new dependancy called MythicLibs v1.0.1
https://dev.bukkit.org/bukkit-plugins/mythiclib/

Is it possible to update depenizen with this new version of MythicMobs and maybe MythicLibs to not have an error on the console ?
Regards

**Comment by Morphan1** [comment]
Thanks for your suggestion! It has been added to the latest build
http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/
