### ISSUE TITLE
TerrainControl location.tc_biome.temperature

### ISSUE THREAD

**Issue by NLBlackEagle** [DenizenScript/Depenizen#126]
Hello,

I'd like to request a tag for my TerrainControl project once again, this time I'm planning to introduce future proof dynamic weather into NLBlackEagle's Realm however to do this and make this Denizen-Noob proof I would need a new tag that defines the terraincontrol temperature of a biome.

With this tag I'll be able to assign special scripts for each temperature value which goes from 0.0 till 10.0 within terraincontrol.

Thanks alot in advance!

**Comment by Fortifier42** [comment]
Added https://github.com/DenizenScript/Depenizen/commit/2f9614422b0d4b5e0a073ab08762da45238c2c1b waiting on a build
