### ISSUE TITLE
Mythicmobs 2.5.1 support

### ISSUE THREAD

**Issue by avatario** [DenizenScript/Depenizen#128]
https://www.spigotmc.org/resources/mythicmobs.5702/

2.60 is nearing release, but the 2.5.1 is super important as it fixed the 1.10.2 support of libdisguses v.9.0.9

can you add 2.5.1 support i get internal exceptions when i try to run depenizens  with 2.5.1.

**Comment by Morphan1** [comment]
Sorry for the delay! I've pushed an updated link to MythicMobs... Although it seems that there weren't actual code changes, which is odd. If you still get exceptions from the latest build, please let me know! (And include a pastebin link or the sort with the full error)

The latest build, as always, is here
http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/
