### ISSUE TITLE
Quest list active and completed quest

### ISSUE THREAD

**Issue by monnierant** [DenizenScript/Depenizen#131]
Hi

It's very nice to get a quest extention but it would be nicer to get a list of the active quest and completed quest.

Getting only the number of active and completed quest is less usefull and does not cover a lot of situation

**Comment by Morphan1** [comment]
Thanks for your suggestion! It has been added to the latest build
http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/

```
<p@player.quests.active_names>
<p@player.quests.completed_names>
```
