### ISSUE TITLE
FactionsUUID Hook issue

### ISSUE THREAD

**Issue by Laos1996** [DenizenScript/Depenizen#132]
http://pastebin.com/rs07Jt0M

**Comment by Morphan1** [comment]
I've pushed a strange workaround to stop the errors, but please note that we can't support forks of plugins (such as FactionsUUID) without great difficulty, if it would be possible at all. Usually, forks like this keep most of the same internal names, which causes lots of incompatibilities. This case seems to be no different. So while the error *might* not show, you won't actually be able to use the Factions functionality with Depenizen. I apologize for any inconveniences that may cause.
