### ISSUE TITLE
PlotSquared Support

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Depenizen#133]
Greeting,

I made this support request for the plugin PlotSquared
https://www.spigotmc.org/resources/plotsquared.1177/
Currently Depenizen support the old PlotMe (the author had [almost] dropped support for now) and everyone now use PlotSquared, it will be great if Depenizen can support PlotSquared !

Could Depenizen support PlotMe and PlotSquared at the same time ?

Regards.

**Comment by Morphan1** [comment]
#101
