### ISSUE TITLE
MythicMobs 2.5.11 support 

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Depenizen#136]
Hi, there's recently been a number of changes to the MM API, and the latest official release (dev builds too but meh) no longer works with Depenizen.
Xikage has not yet provided API documentation but plans to do so uh, "soon".
https://dev.bukkit.org/projects/mythicmobs/files/2372272

Mostly asking because the mythicspawn command isn't working anymore.
Thanks!

**Comment by Rickytehduck** [comment]
Expanding on this, here's the javadoc for the tentatively renamed 4.0.0 update.
Xikage will be filling this out more soon, but hopefully this helps you.
http://mythicmobs.net/javadocs/

Thanks again!

**Comment by mcmonkey4eva** [comment]
I did the 2.5.11 update earlier today, completing this issue.
A new one can be opened when @Xikage is done with his plans to randomly reformat the API for the eighteen time in a row, and has released yet another majorly breaking update.
