### ISSUE TITLE
Mythicmob feature suggestion

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Depenizen#140]
First of all thank you for your great plugin.

I want the function that cancel to mythicmob's drop item and xp.
Because I need to add some flag or nbt (attribute) at droped item.
The determine command in mythicmob death event is working but error showed.
So if you okay,
Make determine command work or cancel the drop items and experience points.

**Comment by mcmonkey4eva** [comment]
For the specific case of mythicmobs, you might have better luck with https://github.com/BerndiVader/mmDenizenAddon ?
