### ISSUE TITLE
Endless "Pinging..." with "on proxy server list ping" event

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Depenizen#141]
Hey Morph,

I am using the "on proxy server list ping" event lately to change the Server MOTD. Now my server sometimes keeps pingin forever. Using latest builds (updated yesterday).

This is the error:
http://one.denizenscript.com/paste/39904

**Comment by GomaTerzu** [comment]
Still happens

http://one.denizenscript.com/paste/40020

**Comment by mcmonkey4eva** [comment]
I imagine this is connected to https://github.com/DenizenScript/Depenizen/issues/146 somehow actually

**Comment by mcmonkey4eva** [comment]
Still happens?

**Comment by GomaTerzu** [comment]
Don't know. I stopped using the "on proxy server list ping" event because nothing happend here.

**Comment by mcmonkey4eva** [comment]
:/

**Comment by mcmonkey4eva** [comment]
Closing as there's no current replication by anyone
