### ISSUE TITLE
MythicMobs 4.0.0 update

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Depenizen#142]
Hi, this should be the last API change as far as MM is concerned, according to Xikage. 
Pretty please can we get an update?

The javadoc:
http://mythicmobs.net/javadocs/
The new update:
https://dev.bukkit.org/projects/mythicmobs/files/2382591

Thanks.

**Comment by Morphan1** [comment]
I updated the link. Here's hoping I'll never have to again! 🥂 Latest builds, as always, are here
http://ci.citizensnpcs.co/job/Depenizen/lastSuccessfulBuild/
