### ISSUE TITLE
Socket disconnects while using the bungee command

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Depenizen#146]
Hey Morphan, I am gettin a lot of disconnects from the bunbgee socket lately when I use the bungee command to send data to other conected server. My password is far too easy already.

I was able to catch this error

http://one.denizenscript.com/paste/40019

**Comment by mcmonkey4eva** [comment]
Still happens?

**Comment by GomaTerzu** [comment]
This seems to be better atm. I could close this
