### ISSUE TITLE
griefprevention error

### ISSUE THREAD

**Issue by econowill** [DenizenScript/Depenizen#147]
current depenizen has error with griefprevention.

this is error logs.
http://old.mcmonkey.org/paste/40102

and i used this script.
http://one.denizenscript.com/paste/40104

**Comment by BlackCoyote** [comment]
You're not specifying the full syntax for the event, you either do;

```on gp player enters <gpclaim>:```
for specific events, where <gpclaim> is replaced by a specific input by you, or
```on gp player enters gpclaim```
  for the generic event that will fire for all

**Comment by econowill** [comment]
ok thanks
