### ISSUE TITLE
questions about areashop

### ISSUE THREAD

**Issue by econowill** [DenizenScript/Depenizen#149]
i have a questions about tag related areashop plugins.
 a tag <player.areashop.owned> is not woks, just return only null
is there a something i missed? surely installed depenizen bukkit, practically used, also areashop plugins

here is the logs.
http://old.mcmonkey.org/paste/40293

thanks

**Comment by Noiknez** [comment]
I also use AreaShop, and this error is annoying

**Comment by mcmonkey4eva** [comment]
Any associated error messages? Did AreaShop load correctly? Can you post a startup log?

**Comment by Noiknez** [comment]
Depenizen started correctly with AreaShop :

> [22:52:08 INFO]: +> [DepenizenPlugin] AreaShop hooked, enabling add-ons.

Console and In-game information can be found here : [Image Link](https://prnt.sc/gxu2c1)

**Comment by mcmonkey4eva** [comment]
... why did you censor your username?
And thanks for clarifying the issue!

**Comment by Noiknez** [comment]
I censor it because I just don't like to show what minecraft account I am using when putting an image on the internet, lol.
