### ISSUE TITLE
pvpArena tag problem

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Depenizen#152]
Hello,

I try to use `<player.pvparena.in_arena[]> ` tag. Documentation say if no arena specified, return true if player is in any.

Instead, i have 
![image](https://cloud.githubusercontent.com/assets/4788317/24770370/02b88cbe-1b0a-11e7-997a-c6913acf3410.png).

I must specify the arena or it's a bug ?

**Comment by mcmonkey4eva** [comment]
remove the `[]`

**Comment by Oruss7** [comment]
Ok ^^ thanks
