### ISSUE TITLE
Wrong attribute for MobArena

### ISSUE THREAD

**Issue by SaitDev** [DenizenScript/Depenizen#153]
`<mobarena@mobarena.players.in_lobby>` currently doesnt work
Please change line
https://github.com/DenizenScript/Depenizen/blob/master/bukkit/src/main/java/com/denizenscript/depenizen/bukkit/objects/mobarena/MobArenaArena.java#L229

to ` if (attribute.getAttribute(2).startsWith("in_lobby"))`
Thanks

**Comment by mcmonkey4eva** [comment]
Fixed + jenkins built. Thank you for the precise info to quickly fix the bug!

**Comment by SaitDev** [comment]
Super fast response! Glad to help your great work a bit
