### ISSUE TITLE
VanishNoPacket Support

### ISSUE THREAD

**Issue by GershonR** [DenizenScript/Depenizen#156]
Can we get VanishNoPacket support for <p@player.is_vanished>
https://dev.bukkit.org/projects/vanish

Thank you

**Comment by BlackCoyote** [comment]
it'd probably be a lot  easier for everyone including yourself to replace that plugin with denizen entirely. It would only take a few lines of script, using the hide_entity mechanism

**Comment by GershonR** [comment]
I mostly use it for its other features such as silent chest, silent join, effects etc.

**Comment by Mwthorn** [comment]
I've noticed that VanishNoPacket is VERY outdated and has some flaws in its code. I think its better to support something like SuperVanish instead: https://www.spigotmc.org/resources/supervanish-be-invisible.1331/

**Comment by mcmonkey4eva** [comment]
closing for non-response
