### ISSUE TITLE
Support for LibsDisguises

### ISSUE THREAD

**Issue by applepower34** [DenizenScript/Depenizen#157]
Could we get support for disguising entities with LibsDisguises?

https://www.spigotmc.org/resources/libs-disguises.32453/

There could be a command like `disguise [<dEntity to disguise>] [<Disguise Type>] (Disguise options)`

Tags could be like `<e@entity.disguise>` to get the disguise of an entity if the entity is disguised and `<e@entity.disguise.options>` to get any options applied to a disguise.

An event could be something like `on entity disguised`

Thanks!

**Comment by mcmonkey4eva** [comment]
This has been added! :D
