### ISSUE TITLE
Console error anytime skyblock player extenstion being generated

### ISSUE THREAD

**Issue by SaitDev** [DenizenScript/Depenizen#158]
Console error: https://pastebin.com/Gq0Q8BWp

Please move lines 35-37 https://github.com/DenizenScript/Depenizen/blob/master/bukkit/src/main/java/com/denizenscript/depenizen/bukkit/extensions/askyblock/ASkyBlockPlayerExtension.java#L35#L37
above line 30

I'm not sure it will fix, not tested yet

**Comment by mcmonkey4eva** [comment]
RE your suggestion: That's... not how Java code works. 0.o
RE your error: The error was within the `ASkyBlockAPI` code according to that, not Depenizen...

**Comment by SaitDev** [comment]
Ah okie, i will report this to ASkyBlock
