### ISSUE TITLE
ShopChest support

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Depenizen#164]
Hi,
The plugin ShopChest need to be supported by depenizen for different tag :
- The ShopChest location
- the ShopChest owner
- an ShopChest creation event
I just need this two tag, but maybe more tag will be great
https://www.spigotmc.org/resources/shopchest.11431/
The development of this plugin is very active

**Comment by Arctomium** [comment]
Why not just make your own alternative in Denizen? Wouldn't be that hard to code I made a whole shop GUI system for my network.

**Comment by Noiknez** [comment]
Good idea, but coding the MySQL part of denizen is difficult

**Comment by Noiknez** [comment]
Development is not active anymore and I will use an Denizen alternative

**Comment by mcmonkey4eva** [comment]
@Noiknez ShopChest isn't developed anymore, you mean?

**Comment by Noiknez** [comment]
I mean, 
The last commit in github was 2 month ago : https://github.com/EpicEricEE/ShopChest

We have also 2 issues posted in August that remains unanswered

**Comment by mcmonkey4eva** [comment]
:/
