### ISSUE TITLE
TRACKS for LuckyPerms

### ISSUE THREAD

**Issue by JumpieDenizen** [DenizenScript/Depenizen#169]
Hey there,

This is Jumpie here.

Can we get TRACKS support for LuckyPerms added?

Here is the API docs:
https://github.com/lucko/LuckPerms/wiki/Developer-API

Basically, you can have groups in LP, and then you group those groups into tracks that players can ascend or descend. Like ladders in other popular perm plugins.

I was hoping to see a tag that goes like this:

<p@player.in_track>
Which would return any tracks that the player might be in.

It could be used in conjunction with <in_group> like:
<p@player.in_track[<some_track_name>].in_group>
Which would return groups that are in a specific track

Or
<p@player.in_track.contains[track_one].in_group>
Which would return groups in track called track_one

Thanks guys

**Comment by mcmonkey4eva** [comment]
Added
