### ISSUE TITLE
Add Plotsquared Support to Depenizen

### ISSUE THREAD

**Issue by Arctomium** [DenizenScript/Depenizen#170]
Name: Plotsquared
Location: https://www.spigotmc.org/resources/plotsquared.1177/
Features Requested:

- Denizen hooks and commands for all the Plotsquared commands (Would mean we could use custom commands instead of the standard /plot)
- Ability to get entire plot cuboid
- Tags for all Plotsquared variables such as owner, price, trusted users, etc.
- Any other features that would be a good idea?

**Comment by mcmonkey4eva** [comment]
Already supported 0.o
