### ISSUE TITLE
Query placeholderapi with treating as from a player

### ISSUE THREAD

**Issue by SaitDev** [DenizenScript/Depenizen#171]
Many placeholder base on each player but `<placeholder[<name>]>` will only use player who trigger the script. So if we featch the placeholder %player_ping% or something like that from console, we cant get the player's ping but null.
It would be greate if we have <p@player.placeholder[]> to query the placeholder as a player

**Comment by mcmonkey4eva** [comment]
use `player:` argument on the line you're reading in.
EG:
`- define val <placeholder[player_ping]> player:bob`
where bob can be swapped for a tag that returns a player of course.

Also, of course, for most "standard" placeholders, just use the relevant tag instead.
In that case, `<player.ping>`

**Comment by SaitDev** [comment]
Thanks for the help. It works as expect. I wonder, argument player: for placeholder[] only works on define command? And yes, Im just trying to interact with some plugins that placerholderapi supported

**Comment by mcmonkey4eva** [comment]
Works on any and every command in Denizen!

**Comment by SaitDev** [comment]
Thank for the info. I'll mark this as solved since It've already had solution
