### ISSUE TITLE
Support for Vehicles Plugin

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#172]
Its not minecart or boats. I'm talking about this plugin:
https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/

Mainly looking for the event when a vehicle is created.

Since the plugin is payed. The developer has provided an empty jar file with only API included.

**Comment by mcmonkey4eva** [comment]
and how do you propose we test anything we add lol

**Comment by mcmonkey4eva** [comment]
Did I forget to post here that we are not going to support premium plugins? cause that's a thing lol
