### ISSUE TITLE
Tags - Towny flag

### ISSUE THREAD

**Issue by WaterQuarks** [DenizenScript/Depenizen#177]
Requesting:

<player.town.has_explosions> -> true/false, does the Town has explosions enabled?
<player.town.has_mobs> -> true/false, does the Town has mobs enabled?
<player.town.has_pvp> -> true/false, does the Town has PvP enabled?
<player.town.has_firespread> -> true/false, does the Town has fire spread enabled?
<player.town.has_taxpercent> -> true/false, does the Town has taxing by percentage enabled?
<player.town.plottax> -> taxes collected from each resident daily, per plot that they own.
<player.town.plotprice> -> default cost of plot for the town.

also, if its possible, a tag that displays all Towns as a dList.

**Comment by mcmonkey4eva** [comment]
Shouldn't the last two not have `has_` on them?

**Comment by WaterQuarks** [comment]
my mistake, edited the request

**Comment by GershonR** [comment]
Request:

<world.town.list> -> get all towns in a world

**Comment by mcmonkey4eva** [comment]
added
