### ISSUE TITLE
Add Support for Residence

### ISSUE THREAD

**Issue by Arctomium** [DenizenScript/Depenizen#180]
Just wondering if you could add support for this plugin known as Residence which is a very handy land/plot claiming plugin that would be perfect for my NPC building schematic system if it could be added in.

Github Link: [https://github.com/Zrips/Residence](https://github.com/Zrips/Residence)

**Comment by Morphan1** [comment]
This already exists, to an extent.

https://one.denizenscript.com/denizen/tags/Residence
https://one.denizenscript.com/denizen/evts/Residence

If you need anything specifically supported in it that isn't already, please open a new issue for that.
