### ISSUE TITLE
Disguise option for self-disguise

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#187]
Currently you cannot view your own disguise when you are disguised. Maybe make an option for that?

option could be included in the command arguement as:
self: true/false

At default, this should be true (if not specified) to see their own disguise when testing first time.

**Comment by mcmonkey4eva** [comment]
For LibsDis? Like, the plugin you code support for here yourself?

**Comment by mcmonkey4eva** [comment]
Added
