### ISSUE TITLE
[REQUEST] Open Terrain Generator Compatibility

### ISSUE THREAD

**Issue by Ugikie** [DenizenScript/Depenizen#188]
Hey guys,
This generation plugin is a fork of Terrain Control, which is already compatible with Depenizen. I was wondering if someone could take some time (probably barely any) to get this OTG plugin functioning similarly in Denizen? I just need to be able to use <location.otg_biome> just like <location.tc_biome> works currently with Depenizen.  I'm sure it wont be that hard, as the two plugins are practically identical.

That is all I need it for, so if someone could please find a way to add that sometime soon, it would be greatly appreciated!

https://www.spigotmc.org/resources/open-terrain-generator-otg.51373/

**Comment by Morphan1** [comment]
I mean I did it. I don't know why, but I think I did it.
