### ISSUE TITLE
Dice Furniture Integration

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Depenizen#194]
#Due to the fact Denizen's armorstand system is very limited as well as has issues with determining variables with armorsands in relation with the `on player clicks at entity` I am asking we add integration with the [Dice Furniture](https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/) plugin which would allow for the following features to be added and used within Denizen:

- Change/Replace the item or model being displayed in the armorstand
- Better armorstand entity detection

**Reasons for this to be added:**
- Color Changing on Player Clicks (Allows the change of color on certain materials used in the furniture by checking an event with the player clicking the furniture with a dye and then change or replace the item/model with a different model using that color on the selected material)
- Custom Inventories & Storage (Using a custom click event which DiceFurniture uses could allow for the use of custom storage through furniture, etc. as well as the potential for new crafting interfaces if done correctly)
- Dynamic Items & Blocks (An example would be a bookshelf with 9 other armorstands inside it which opens a custom inventory which only books can be added into and when added would show a 3D or custom book model inside the shelf in the corresponding slot)
- Custom Mobs (Using entity items/models and moving armorstands in various variations would allow for the addition of completely new mobs within vanilla Minecraft)
- Vehicles (Similar to the method used for custom mobs new vehicles could be added in such as flying, land and aquatic vehicles)

**Comment by mcmonkey4eva** [comment]
I don't see any reason to use this over some scripts.
See for reference: https://one.denizenscript.com/denizen/repo/entry/98

**Comment by Morphan1** [comment]
I also can't find a good enough reason to add support for this. If you're dissatisfied with armor stand support somehow, post an issue over on the Denizen repo and maybe we can get some things implemented. But honestly, I think it's a solid enough system and I can't see anything that plugin provides besides pre-existing yml-based armor stand furniture and an... _interesting_... code base. Feel free to discuss more on Discord.
