### ISSUE TITLE
Cartographer support

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Depenizen#199]
Hello, the plugin is now open source : https://github.com/BananaPuncher714/Cartographer

(link to the other github issue : https://github.com/DenizenScript/Depenizen/issues/178 )

**Comment by mcmonkey4eva** [comment]
Looking at that code brings me physical pain, it's that bad. There's not even a build file included...

**Comment by mcmonkey4eva** [comment]
Going to refuse support here on the grounds that the linked plugin is a wreck of unsupported incoherently built shite.
Going to also recommend you not buy the premium plugin, based on the visible lack of quality in the code the developer _is_ willing to post publicly.
