### ISSUE TITLE
MagicSpells Support

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#202]
https://github.com/TheComputerGeek2/MagicSpells

Mainly a tag to check a player's mana.

And maybe some events from here: http://nisovin.com/magicspells/doc/

**Comment by SXRWahrheit** [comment]
bump

events (so I can cleanly make spells that trigger scripts) would be dope

**Comment by SXRWahrheit** [comment]
I'm not sure which event would use it, but could you add `determine`s for spell costs?

Usage would be e.g. determining whether to use items or mana depending on what equipment a player is wearing.

**Comment by mcmonkey4eva** [comment]
Done by #238
