### ISSUE TITLE
DeathMessagesPrime support

### ISSUE THREAD

**Issue by SXRWahrheit** [DenizenScript/Depenizen#203]
I think I can already use the `on player dies` event, but `on deathmessagesprime death` or something appropriately-named might work more reliably.

A tag for the message being sent would be great.

My desired functionality is to output a message on Discord when a player dies by using dDiscordBot. I have a working setup right now, but <context.message> only returns the vanilla death message, not my fun ones.

https://www.spigotmc.org/threads/deathmessagesprime.48322/page-22#post-2462605

https://www.spigotmc.org/resources/deathmessagesprime.3789/

**Comment by mcmonkey4eva** [comment]
What.
Why.
No.
Use any of the existing basic Denizen events for that, such as `on player death` or `on player receives message` or whatever else.
You can even `- yaml load` in the config for that plugin to get the list of messages you have set on it
