### ISSUE TITLE
Worldguard region event

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Depenizen#213]
Would it be possible to add an event that would fire when a new Worldguard region is created?

Thanks for looking into it.

**Comment by Mwthorn** [comment]
I have been trying to find the event: "region being created" within WorldGuard but I have only found this in the documentation: https://worldguard.enginehub.org/en/latest/developer/regions/events/
There are also some Blacklist events but they seem unrelated. Maybe we need a request WorldGuard to add this event? 

Alternatively, I suggest using denizen scripts and have events like "on region command" or a task script that creates worldguard regions.

Worldguard docs: http://docs.sk89q.com/worldguard/apidocs/

**Comment by Mwthorn** [comment]
There's an alternative to WorldGuard events, would it be a reliable solution? 
Or maybe use their logic to make these events ourselves?
https://dev.bukkit.org/projects/worldguard-region-events
https://www.spigotmc.org/resources/worldguard-events.65176/
https://www.spigotmc.org/resources/wgregionevents-continued.15946/

This can pretty much also be made straight in a Denizen script, checking the player's movement and use region tags to detect.

**Comment by mcmonkey4eva** [comment]
Yeah that plugin is just doing the same essential logic as the notable cuboid enter/exit event does.

**Comment by mcmonkey4eva** [comment]
Closing until WorldGuard adds an event for this.
