### ISSUE TITLE
Expand Sentinel Support

### ISSUE THREAD

**Issue by Velinquish** [DenizenScript/Depenizen#214]
Would it be possible to give Depenizen the ability to edit Sentinel NPC statistics like Health, Attack, and such as well as Targets?

**Comment by mcmonkey4eva** [comment]
Those aren't statistics, statistics are the output of `/sentinel stats`.

Aside from that: yes could be added, though not super needed... you can do:

```
- execute as_server "npc sel <npc.id>" silent
- execute as_server "sentinel health 50" silent
```

with any plugin or command to control it.
It's generally more important for Depenizen to add tags and events, as those can't really be replicated without them being explicitly added.
