### ISSUE TITLE
GriefPrevention owner tag

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Depenizen#215]
There is currently no way to get the owner of any GP claim, we need something like <l@location.griefprevention.claim.owner>.

There is also no way to get trusted players, so <l@location.griefprevention.claim.trusted> would be nice too.

**Comment by lmorgh** [comment]
Can we expect any development on this? Asking for a friend. *wink wink*

**Comment by mcmonkey4eva** [comment]
Done by #238
