### ISSUE TITLE
Dice Furniture / Furniture Lib

### ISSUE THREAD

**Issue by OpalMoonstride** [DenizenScript/Depenizen#219]
I have made a request on the author's page, but I see a suggestion to request support here, too. 

I'm hoping for support for Furniture Lib (Used for Furniture Maker, and Dice Furniture), so that my players may make functional armor stand furniture. 
Here's a link: https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/

Thanks!

**Comment by mcmonkey4eva** [comment]
Have you read the response to the previous issue making the same request? https://github.com/DenizenScript/Depenizen/issues/194
