### ISSUE TITLE
Depenizen Error in current 1.13

### ISSUE THREAD

**Issue by xr001** [DenizenScript/Depenizen#220]
This is an error I receive in console when attempting to load the current build of Depenizen against the current 1.13 dev build of Spigot.

https://one.denizenscript.com/haste/49064

**Comment by axemwa** [comment]
Also getting this error in 1.12.2 

https://pastebin.com/N5siFBvb

**Comment by mcmonkey4eva** [comment]
@axemwa Depenizen build 411 is compatible with latest dev builds of Denizen (not the release builds). Either downdate Depenizen a few versions or update Denizen from http://ci.citizensnpcs.co/job/Denizen_Developmental/

**Comment by mcmonkey4eva** [comment]
should be fixed in Depenizen build 412

**Comment by axemwa** [comment]
oh I see, oops I was using this one http://ci.citizensnpcs.co/job/Denizen/ thanx :)

**Comment by xr001** [comment]
Depenizen 412 is currently experiencing the same issue as previous builds in 1.13.1

**Comment by xr001** [comment]
![console](https://user-images.githubusercontent.com/41926658/45132548-620f9d00-b15f-11e8-98dc-d04be0a2ba6e.png)

**Comment by mcmonkey4eva** [comment]
That is an issue with LibsDisguises (or at least with the link between Depenizen and that plugin)

**Comment by xr001** [comment]
Hmm kinda sucks that it complete shuts down Depenizen. I could live with it just not hooking to libsdisguises as we use it with MythicMobs more than anything.

**Comment by xr001** [comment]
After updating Libsdisguises as I didn't realize they had, I now get this error:
![console](https://user-images.githubusercontent.com/41926658/45133130-b9167180-b161-11e8-9776-d243ca4f43fc.png)

**Comment by mcmonkey4eva** [comment]
build 414 (just built) fixes the second error and catches the first error more safely
