### ISSUE TITLE
Ability to Get Faction Land as Cuboid

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Depenizen#222]
I want a tag/s to be able to get faction land as a cuboid from the very bottom all the way to the top for each claim since some faction areas can be made not cubed and so a tag to get all the claims in a dList which can then be tagged using the cuboid one to get all claims as multiple cuboids.

**Comment by mcmonkey4eva** [comment]
I believe factions works on a chunk basis, so a tag for this would return a list of chunks (which can then be easily converted to cuboids via a `.parse[cuboid]` tag).
