### ISSUE TITLE
Client-side worldborders (WorldBorderAPI support?)

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#226]
I found this plugin that adds client-side worldborders using packets:
https://github.com/yannicklamprecht/WorldBorderAPI
Should it be implemented directly into Denizen or be supported in Depenizen?

**Comment by mcmonkey4eva** [comment]
This is very simple to implement ourselves (it just sends a world border packet), please post in Denizen: https://github.com/DenizenScript/Denizen-For-Bukkit/issues
