### ISSUE TITLE
"on player activates mcmmo ability" event

### ISSUE THREAD

**Issue by waterquarks** [DenizenScript/Depenizen#230]
PLEASE

**Comment by WaterQuarks** [comment]
if its any help:
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/events/skills/abilities/McMMOPlayerAbilityActivateEvent.java
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/events/skills/abilities/McMMOPlayerAbilityDeactivateEvent.java

**Comment by SXRWahrheit** [comment]
when this gets revisited, note that mcmmo is about to undergo / is undergoing a major overhaul

**Comment by mcmonkey4eva** [comment]
Done by #238
