### ISSUE TITLE
Latest Depenizen incompatibility with worldgard 6.2.2

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Depenizen#233]
The output of /version on my server is: CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

The output of /version denizen on my server is: v1.0.3-SNAPSHOT (build 454-DEV)

Depenizen version : v1.0.0 (build 421)

WorldGuard version : WorldGuard v6.2.2-SNAPSHOT;8eeab68

Server log : https://one.denizenscript.com/haste/50675

(If relevant) A link to a paste of a script demonstrating the issue: https://one.denizenscript.com/haste/50676

The issue is:
I updated the server with the latest version of Denizen (DEV), Depenizen and Citizens2 and I get a spammy error on my console

**Comment by mcmonkey4eva** [comment]
I don't know why this would fail.
`Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard `
WorldGuard loaded fine.
That class exists: https://github.com/sk89q/WorldGuard/blob/master/worldguard-core/src/main/java/com/sk89q/worldguard/WorldGuard.java

Is WorldGuard working normally on that server?

**Comment by Noiknez** [comment]
Yes worldguard function at it should be

**Comment by Noiknez** [comment]
![image](https://user-images.githubusercontent.com/20723083/48428934-539bbe00-e76c-11e8-873d-238a6e5c08c6.png)

**Comment by Morphan1** [comment]
The latest Depenizen is only compatible with the latest version of WorldGuard (7.x.x). We cannot support older versions due to a significant API change during the 1.13 update. Either downgrade Depenizen or upgrade your server to 1.13.2
