### ISSUE TITLE
Support for <item.worth> tag

### ISSUE THREAD

**Issue by Chalwk77** [DenizenScript/Depenizen#234]
Hello. I realize there is support for Essentials which allows the use of the <item.worth> tag in a Denizen/Depenizen script, however, I do not use Essentials. Instead, I use CMI (Content Management Interface) which also has a /worth system. I am trying to query the 'worth' of an item in a denizen script but I am unable to hook into CMI. Any help with this will be appreciated!

Link to CMI:
https://www.spigotmc.org/resources/cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

**Comment by mcmonkey4eva** [comment]
Premium-only plugins cannot and will not be supported.

**Comment by mergu** [comment]
Hey Chalwk77,

If you're trying to do this in a Denizen script then as stated before we can't support premium plugins. However, you may be able to run the command and parse its output via Denizen's `execute` command.

If you execute the command  (for example, `- execute as_server "worth <item.material.name>" save:blah`) you can access its output via `<entry[blah].output>`.

If you need more help, you can join our help channel on Discord: https://discord.gg/Q6pZGSR
