### ISSUE TITLE
MythicMobs Items

### ISSUE THREAD

**Issue by bushuaichen** [DenizenScript/Depenizen#235]
Hope you can call the items in Mythic Mobs directly,
        - random:
          - repeat 1: 
            - give i@<mm_item>

**Comment by mcmonkey4eva** [comment]
Not _that_ directly but a tag that translates an mm item name to a valid dItem would be handy

**Comment by bushuaichen** [comment]
> Not _that_ directly but a tag that translates an mm item name to a valid dItem would be handy
> 
> Essentially the same setup, but you'd do:
> 
> ```
> - give <mm_item[some_item_name]>
> ```
> instead of `- give i@some_item_name`

Is this an existing function or a planned one?

**Comment by mcmonkey4eva** [comment]
That's a likely way this request could be functionally added.

**Comment by SXRWahrheit** [comment]
It's likely that you're already aware, but fyi you can do this with mmDA until Depenizen adds support

https://github.com/BerndiVader/MythicDenizenAddon/blob/master/documentation/tags.md

**Comment by mcmonkey4eva** [comment]
This was added by https://github.com/DenizenScript/Depenizen/commit/15ee186646b662e8bbeb599086dd0dfef87c02dc as `<mythic_item[somename]>`
