### ISSUE TITLE
FAWE brush info 

### ISSUE THREAD

**Issue by Dad3** [DenizenScript/Depenizen#236]
I am very motivated to make this plugin https://bukkit.org/threads/worldedit-and-voxelsniper-expansion-brushinfo.475781/ 

I need a way to get the brush type, brush size, pattern, and //mask, and a way to check if player's brush is indeed a brush tool. 
I am not sure how this would work exactly, since multiple players can have multiple brushes.
Let's say player Notch does //brush sphere grass 5, then I need a way to detect his brush tool and set its name/lore to brush type (sphere) size (5) and pattern (grass)

heads up, patterns can get complicated since they are not just blocks.
FAWE has public API and support on their discord if that might help with this. Thank you so much!

**Comment by mcmonkey4eva** [comment]
That'd be just a WorldEdit linkage, not FAWE (FAWE is an extension of WE, not an alternative)

**Comment by mcmonkey4eva** [comment]
Far from perfect but
`<p@player.we_brush_info[(<item>)]>` returns `dList`.
```

        Returns information about a player's current brush for an item.
        If no item is specified, will be based on their held item.
        Output is in format: type|size|range|material
        
        Note that some values may be listed as "unknown" or strange values due to WorldEdit having a messy API (no way to automatically stringify brush data).
```
