### ISSUE TITLE
<p@player.we_brush_info[(<item>)]>  error

### ISSUE THREAD

**Issue by Dad3** [DenizenScript/Depenizen#237]
my script
`test:
    type: task
    script:
    - narrate "test: <player.we_brush_info>"`

error: https://pastebin.com/4b8hdFCR

**Comment by mcmonkey4eva** [comment]
What Spigot version, what WE version? use `/version` and `/version worldedit`

**Comment by Dad3** [comment]
[07:07:57 INFO]: This server is running Paper version git-Paper-1593 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

[07:08:37 INFO]: WorldEdit version 6.1.7;dd00bb1

**Comment by Dad3** [comment]
Im using fawe also w.e 7 is very broken no one uses it

**Comment by mcmonkey4eva** [comment]
More than four thousand servers use it according to https://bstats.org/plugin/bukkit/WorldEdit

**Comment by Dad3** [comment]
@mcmonkey4eva find me a single creative server with that worldedit version, its not possible there are none

**Comment by mcmonkey4eva** [comment]
Unreasonable claim but irrelevant.

Depenizen latest is compatible with WE latest. If you have issues with WE, ask them to fix it.
