### ISSUE TITLE
On Getting Variables

### ISSUE THREAD

**Issue by bushuaichen** [DenizenScript/Depenizen#240]
For flip-flops on entity kills entity: [on player kills player]

I don't know how to get the names of two players.
Two players refer to the killer and the victim hoping to help me.

**Comment by mcmonkey4eva** [comment]
Event context tags are listed in the event meta: https://one.denizenscript.com/denizen/evts/kills
You might want to watch the Denizen tutorial videos: https://one.denizenscript.com/denizen/vids (starting around the video 'your first tags' and going in order from there til the main series ends)
You might also join Discord if you want to ask questions / get guidance / etc: https://discord.gg/Q6pZGSR
