### ISSUE TITLE
DeathMessage variable %weapon% is replaced with '???' in chat.

### ISSUE THREAD

**Issue by NPCtom** [DenizenScript/Depenizen#241]
I have a custom death message for PlayerMeele `"&E%plrtag% was &CMURDERED &Eby %killer% with a &C[%weapon%&f]!"`

But in chat it say's `JJBMartin was MURDERED by NPCtom with a [???]!`

**Comment by mergu** [comment]
Uh

Did you post this in the right place? This is the Depenizen issue tracker (an addon plugin for Denizen, a scripting language).
