### ISSUE TITLE
DiscordSRV Support

### ISSUE THREAD

**Issue by robgob** [DenizenScript/Depenizen#243]
Would it be possible to add support for this plugin? This API allows you to make discord -> to -> minecraft commands and so on.

You could for example have player stats displayed on your discord for all to see, or even have special perks sent to discord from donating/voting on your server. Server Raid alerts, or say someone's base is being pummeled on factions, they could have discord alerts sent to their DM's.

So many possibilities, would love to see support for this :)

**Comment by mergu** [comment]
Already implemented in https://github.com/DenizenScript/dDiscordBot. Feel free to post issues & feature requests there, and join our discord to learn how to use it: https://discord.gg/Q6pZGSR

**Comment by robgob** [comment]
Awe yeah, that's sick. I will read up on this.

**Comment by mcmonkey4eva** [comment]
Note that that isn't an integration to some external Discord plugin, dDiscordBot is our own Discord/Denizen connection that only requires itself and Denizen!
Works using standard Discord bot stuff
