### ISSUE TITLE
Essentials

### ISSUE THREAD

**Issue by Klawdek** [DenizenScript/Depenizen#245]
One page says essentials is supported anther page does not have it on the list of supported plugins and the page with a list of tags has none for essentials.

**Comment by mergu** [comment]
EssentialsX is supported. I pinged you on discord with the supported features

**Comment by mcmonkey4eva** [comment]
It's listed as supported here: https://github.com/DenizenScript/Depenizen#depenizenbukkit
Which is the only up-to-date list.

If you go on the tag list: https://one.denizenscript.com/denizen/tags/
And CTRL-F "essentials"
You'll find related tags.
You can also go in Discord and type `!search essentials` to find all available Essentials related options.
