### ISSUE TITLE
Error when reloading scripts after installing depenizen

### ISSUE THREAD

**Issue by Klawdek** [DenizenScript/Depenizen#246]
The output of `/version` on my server is: **paste here**
14.02 20:54:50 [Server] INFO This server is running CraftBukkit version git-Spigot-e8ded36-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
14.02 20:54:50 [Server] INFO This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.

The output of `/version denizen` on my server is: **paste here**
14.02 20:55:46 [Server] INFO Denizen version 1.0.3-SNAPSHOT (build 497-DEV)
15.02 14:11:32 [Server] INFO Depenizen version 1.0.0 (build 434)
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
**Describe your issue in full here**
After installing depenizen I get the following error when I restarted server and whenever scripts are reloaded, https://one.denizenscript.com/paste/52370

Also I am running the latest version of mcmmo that is for minecraft 1.12.2

**Comment by mcmonkey4eva** [comment]
update Denizen to latest:
Denizen: https://ci.citizensnpcs.co/job/Denizen_Developmental/

Update mcMMO to latest as well.
You don't seem to be running latest mcMMO based on the error message

**Comment by Klawdek** [comment]
There is no updating mcMMO as I am on the latest version for spigot 1.12.2 the newer versions are for 1.13+

**Comment by mcmonkey4eva** [comment]
There's definitely room to update Denizen though
