### ISSUE TITLE
Spartan Anti cheat support

### ISSUE THREAD

**Issue by Jepijepjep422** [DenizenScript/Depenizen#249]
If you have time can u add support for the anticheat called Spartan?
https://www.spigotmc.org/resources/spartan-anticheat-advanced-detections-hack-blocker.25638/

if its possible adding a violations event that could either be set for a certain violation or for global
on [KillAura/Fly/Speed/Reach/Glide/etc..] [<violations>|1|2|3] violations [in  area]:
then the tags for each hack type and the number of violations that could be paired with the hack type or player: 

<spartan_KillAura> or <player.violations> or <player.spartan_KillAura.violations>

 and a tag for the time between each violations <player.spartan_KillAura.violations_time> and two boolean tags for if spartan identifies that the violation is a false positive or not  and if spartan cancelled the cheat

**Comment by mcmonkey4eva** [comment]
We cannot add support for premium plugins.
