### ISSUE TITLE
WorldEdit brush material never assigned

### ISSUE THREAD

**Issue by wizjany** [DenizenScript/Depenizen#250]
https://github.com/DenizenScript/Depenizen/blob/54f066fa7cc6e143ec060fa6a951d8b5ba7d919e/bukkit/src/main/java/com/denizenscript/depenizen/bukkit/extensions/worldedit/WorldEditPlayerExtension.java#L97

probably should be `materialInfo = `, or else it will always be unknown.

**Comment by mcmonkey4eva** [comment]
Good catch! Fixed, thank you.

Fix is in build DEV-449+
