### ISSUE TITLE
Votifier update

### ISSUE THREAD

**Issue by Jepijepjep422** [DenizenScript/Depenizen#251]
The bukkit votifier is no longer being updated can you move the support into this one instead?
https://www.spigotmc.org/resources/nuvotifier.13449/
this is for the event "on votifier vote" with the event tags: <context.time>, <context.service>, and <context.username>

**Comment by writeescape** [comment]
They all use the same mechanism.

**Comment by Jepijepjep422** [comment]
ahh my bad, i made a script and tested it out a couple of times but it ddnt work. i ddnt knew that it was the firewall's fault.
