### ISSUE TITLE
ViaVersion Support

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#252]
Personally I think it would be pretty cool to check what client version a player is using.

The tag could be <player.client_version> or <player.protocol_id>

API: https://github.com/ViaVersion/ViaVersion/tree/master/bukkit/src/main/java/us/myles/ViaVersion/api

**Comment by SXRWahrheit** [comment]
Bumping this because it would be nice to only nag people about using the version the server is on if they're on a different version

More info here: 

* https://docs.viaversion.com/display/VIAVERSION/Basic+API+usage
* https://jd.viaversion.com/

**Comment by mcmonkey4eva** [comment]
Added by #272
