### ISSUE TITLE
[Sentinel] on sentinel npc attacks: add more context

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Depenizen#253]
Hello,

Can we have more context for this event please ?

Actually (https://one.denizenscript.com/denizen/evts/sentinel):
- <context.entity> returns the entity that the NPC is attacking.

Must have:
- <context.entity> returns the NPC attacking.
- <context.target> returns the entity that the NPC is attacking (like on entity targets event).

Optionnaly:
- <context.reason> return the reason (TYPE_PLAYER,  NAME_REGEX, etc.)

Thanks !

**Comment by mcmonkey4eva** [comment]
`<context.target> returns the entity that the NPC is attacking (like on entity targets event).`
That's what `<context.entity>` already is.

`<npc>` is the Sentinel NPC doing the attack.

There is no conceptual reason available. Sentinel NPCs attack their targets and don't attack non-targets.
