### ISSUE TITLE
Minor comment typo

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#254]
Copy/Paste typo at:
https://github.com/DenizenScript/Depenizen/blob/master/bukkit/src/main/java/com/denizenscript/depenizen/bukkit/objects/luckperms/LuckPermsTrack.java#L30

**Comment by mcmonkey4eva** [comment]
@Mwthorn You made that in a previous PR. Perhaps fix it in your still-in-progress-somehow PR?
