### ISSUE TITLE
Quests tags broken

### ISSUE THREAD

**Issue by SXRWahrheit** [DenizenScript/Depenizen#256]
Quest points work, but the ones about completed and active quests don't.

https://one.denizenscript.com/paste/54093

**Comment by mcmonkey4eva** [comment]
Looks to be a version issue. Depenizen targets Quests `3.3.4` while you are using `3.6.4`
Current version appears to be `3.6.6`, so we should bump to support that

**Comment by SXRWahrheit** [comment]
Versions update fairly frequently these days - subversions at least, anyway. Is strict version checking necessary?

**Comment by mcmonkey4eva** [comment]
It's not version _checking_. It's that we built for (as: wrote code that works for) Quests 3.3.4 and they literally changed things in the code that we reference in some update past that point, breaking Depenizen's link.

**Comment by SXRWahrheit** [comment]
Ah, sorry - your phrasing led me to make a wrong assumption.

**Comment by mcmonkey4eva** [comment]
Fixed for build 464+
