### ISSUE TITLE
SavageFactions Support

### ISSUE THREAD

**Issue by tardreted** [DenizenScript/Depenizen#257]
Requesting tags for The SavageFactions plugin https://www.spigotmc.org/resources/savagefactions-the-ultimate-factions-plugin-1-7-1-13.52891/

Source code: https://github.com/ProSavage/SavageFactions

requested tags: faction.location - faction.power - player.faction - faction.balance - faction.id - faction.home - faction.name - faction.list_factions and if possible a extention to the location tag - location.is_owned.by[<faction>]

**Comment by mcmonkey4eva** [comment]
Unsupportable.
We support the official version of Factions. We functionally _cannot_ support forks of Factions, as we can only support one version of a specific plugin at a time, and it's not worth the effort of building the infrastructure to support multiple versions of one plugin.
