### ISSUE TITLE
Depenizen / PlaceholderAPI

### ISSUE THREAD

**Issue by XxDuckbusterxX** [DenizenScript/Depenizen#259]
Hello, I got a message regarding Depenizen in my console.
Just wanted to tell you this.

`[06:34:30 ERROR]: [PlaceholderAPI] Depenizen is currently using a deprecated method to hook into PlaceholderAPI. Placeholders for that plugin no longer work. Please consult [Morphan1, DenizenScript team] and urge them to update it ASAP.`

**Comment by mcmonkey4eva** [comment]
Update to latest Depenizen build, this was already fixed.
