### ISSUE TITLE
MythicMobs support expansion

### ISSUE THREAD

**Issue by SXRWahrheit** [DenizenScript/Depenizen#260]
## Mobs

https://www.mythicmobs.net/manual/doku.php/databases/mobs/overview
https://www.mythicmobs.net/manual/doku.php/databases/mobs/options
https://www.mythicmobs.net/manual/doku.php/databases/mobs/levels
https://www.mythicmobs.net/manual/doku.php/tutorials/customai
https://www.mythicmobs.net/manual/doku.php/databases/mobs/aigoals
https://www.mythicmobs.net/manual/doku.php/databases/misc/damagemodifiers
https://www.mythicmobs.net/manual/doku.php/databases/mobs/modules/threattables
https://www.mythicmobs.net/manual/doku.php/databases/mobs/modules/immunitytables

## Skills

https://www.mythicmobs.net/manual/doku.php/skills/start
https://www.mythicmobs.net/manual/doku.php/skills/triggers/start
https://www.mythicmobs.net/manual/doku.php/skills/targeters/start
https://www.mythicmobs.net/manual/doku.php/conditions/start

## Items and drops

https://www.mythicmobs.net/manual/doku.php/databases/items/overview
https://www.mythicmobs.net/manual/doku.php/databases/drops/overview

## Spawners

https://www.mythicmobs.net/manual/doku.php/databases/spawners/spawners
https://www.mythicmobs.net/manual/doku.php/databases/spawners/randomspawners

**Comment by mcmonkey4eva** [comment]
Added `mythic_item[name]` tag base, which makes far more sense than `<i@item.mythicmobs.get_item[]>`

Looked into the idea of `<i@item.mythicmobs.internal_itemname>` (would _not_ be named that) but I'm not so confident that's even possible within MythicMobs (converting item stack -> mythicitem).
It's hard to be sure as the MythicMobs website (which features all documentation and even the current jar download) seems to be down at the moment.

**Comment by mcmonkey4eva** [comment]
Closing until issue is cleaned as requested.

**Comment by SXRWahrheit** [comment]
woo, underscores

**Comment by SXRWahrheit** [comment]
Updated as requested

**Comment by quochungudon** [comment]
Did this in progress yet ?

**Comment by SXRWahrheit** [comment]
No. The issue will be closed when the update is complete.

**Comment by mcmonkey4eva** [comment]
Added by https://github.com/DenizenScript/Depenizen/pull/334
