### ISSUE TITLE
WorldEdit Clipboard Support

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#262]
WorldEdit has a clipboard for each player. It would be nice to be able to place a schematic/cuboid into a player's clipboard.
I've done something like this in the past, but that was done using only FAWE's implementation.
The command could be like:
`- fawe clipboard target:<player> filePath:schematics/<def[title]>`
`- fawe clipboard target:<def[value]> cuboid:<def[cuboid]> position:<def[location]>`

The reason that clipboard is an arg and not a command on its own is to allow additional suppot for FAWE such as editing blocks (//walls //sphere //pyramid etc.) or doing a massive schematic paste with undo supported.

**Comment by mcmonkey4eva** [comment]
Depenizen supports WorldEdit.
FAWE is an extension to the WorldEdit API, not a separate plugin.
Any commands/tags/etc. meant to support those plugins will target WorldEdit.
