### ISSUE TITLE
Events on player sends Bungeecord command and/or receives Bungeecord message

### ISSUE THREAD

**Issue by PsychoLynx** [DenizenScript/Depenizen#264]
As requested on Discord, I am making an issue.

I was trying to make a script run upon using the /ban command connected to Litebans on my Bungeecord proxy. However, Denizen/Depenizen doesn't seem to be able to catch this command, nor catch messages originating from the Bungeecord proxy (I tried to get past this limitation by using "on player receives message", but to no avail)

**Comment by mcmonkey4eva** [comment]
Event `on proxy server (<command>) command` or `on proxy server command` is now available!

Receives message is a bit too overkill ... it _could_ be made but I'd rather avoid it if it's not absolutely needed.
