### ISSUE TITLE
Fix Plotsquared Bridge

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Depenizen#265]
Basically the bridge for Plotsquared is broke since one of their more recent updates:
`[15:37:34] [Server thread/INFO]:  ERROR! Cannot load Depenizen bridge for 'PlotSquared': Internal exception was thrown! 
[15:37:34] [Server thread/INFO]:  ERROR! Internal exception was thrown! 
[15:37:34] [Server thread/INFO]:  ERROR! java.lang.NoClassDefFoundError: com/plotsquared/bukkit/events/PlayerEnterPlotEvent
[Error Continued] com.denizenscript.depenizen.bukkit.bridges.PlotSquaredBridge.init(PlotSquaredBridge.java:23)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:70)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:31)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[Error Continued] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:466)
[Error Continued] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:380)
[Error Continued] net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[Error Continued] net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[Error Continued] net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859)
[Error Continued] java.lang.Thread.run(Unknown Source)
[Error Continued] Caused by: java.lang.ClassNotFoundException: com.plotsquared.bukkit.events.PlayerEnterPlotEvent
[Error Continued] java.net.URLClassLoader.findClass(Unknown Source)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] com.denizenscript.depenizen.bukkit.bridges.PlotSquaredBridge.init(PlotSquaredBridge.java:23)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:70)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:31)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[Error Continued] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:466)
[Error Continued] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:380)
[Error Continued] net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[Error Continued] net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[Error Continued] net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859)
[Error Continued] java.lang.Thread.run(Unknown Source)
`

**Comment by mcmonkey4eva** [comment]
Apparently they changed the root package...
