### ISSUE TITLE
Quests Tag & Event Update

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Depenizen#266]
Basically just add more tags and events to link into Quests.

For example linking into the event API to trigger specific events from quests?
`on player questing <quest> breaks block:`

Also more tags based around the actual data it has for example:
`<quests.all_quests>`,`<quests.current_players_questing>`, etc.

**Comment by SXRWahrheit** [comment]
`on player questing quest breaks block` won't work because quests can have spaces in their names - Quests tracks and provides the player-facing quest names, not the internal lines. Also, it can be achieved via an `if` in `on player breaks block`.

`quests.all_quests` can be achieved by parsing the quests file after loading it as a yaml.

`quests.current_players_questing` would require Quests to provide that data, which I don't believe it does.

**Comment by mcmonkey4eva** [comment]
Tags: can do (assuming Quests provides this data to an accessible API), but as Wahrheit mentioned loading the quests YAML is available as a way to do it regardless in the meantime.
Events: not possible and not needed, as Wahrheit explained.

**Comment by Elxafil** [comment]
Reading the YAML file does work but it's not what I need it for, the reasoning behind it is to use Denizen task scripts to dynamically create specific quests with certain variables.

**Comment by SXRWahrheit** [comment]
I don't understand, how would the tags allow you to not have to do that?

**Comment by Elxafil** [comment]
Maybe if you read correctly I also asked for events, why not "on player finishes <quest>" for example? Also I thought I had put in my original issue but obviously not a Denizen command for creating and managing quests from within Denizen itself.

**Comment by SXRWahrheit** [comment]
`on player finishes <quest>` would not be possible for the reasons related to `on player questing quest breaks block`. `on quests player completes quest` with a `<context.questname>` might be doable, though.

As a stopgap, Quests natively implements the ability to run commands on quest completion, which you can use to run task scripts. Those commands support PlaceholderAPI usage for passing any needed contexts.

**Comment by Elxafil** [comment]
Oh cool that's a fair point man, I'll have to look into that although it would still be handy to have a quests dedicated command for dynamic quest creation/modifcation.

**Comment by mcmonkey4eva** [comment]
I think I added basically everything that can/should be reasonably added.

I'm not sure what `current_players_questing` is meant to be, but it's probably something that can be derived from the `PlayerTag.Quests.*` tags.

Any commands needed should be handled via `execute`. If a way to do something is missing... ask the Quests dev to add a command.

Note that you'll need Quests 3.8.0+ to use any of this.
