### ISSUE TITLE
Plotsquared deny tag

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#269]
<PlotSquaredPlotTag.denied>
This should return a list of players who are denied from the plot.

**Comment by Elxafil** [comment]
Couldn't you just do this:
`<server.list_players.exclude[<PlotSquaredPlotTag.trusted]>`

**Comment by mcmonkey4eva** [comment]
@Elxafil Denial is its own system, not simply the inverse of trust.

**Comment by Mwthorn** [comment]
Fixed in https://github.com/DenizenScript/Depenizen/pull/271
