### ISSUE TITLE
Jobs root tag

### ISSUE THREAD

**Issue by smellyonionman** [DenizenScript/Depenizen#276]
I'm writing scripts that use <Jobs> related tags and have noticed that it's reading the actual Names of the jobs, as in the YAML key "Jobs.exampleJob.fullname" from the jobConfig.yml file.
If it was returning just the parent key "Jobs.exampleJob", it would be more useful.

This would give us an internal (hopefully shorter) name to use for Denizen job@ objects while still having access to the fullname key via <player.jobs[exampleJob].name> tag.

Especially since we can name the "Jobs.exampleJob" key whatever we want in jobConfig.yml, this exposes another level of control to us.  In my case I would just rename the keys in jobConfig.yml to match the namespace I've reserved in my Denizen scripts and be done with it forever.

**Comment by mcmonkey4eva** [comment]
This is a limitation of the design of the Jobs plugin itself. As best I can tell, it does not track the key you're referring to, and instead only keeps track of the "full name". We use the API method `Jobs.getJob(string)` to get a job for the Jobs tag.

The change you're requesting makes a lot of sense - I'd suggest sending it to the developer of the Jobs plugin, requesting they track that data and provide corresponding API methods.

**Comment by smellyonionman** [comment]
Thanks for your suggestion, I did and it was committed.  Compiled and returns as intended.  Cheers!
