### ISSUE TITLE
DMSGP: Death messages not showing until player with higher permissions dies

### ISSUE THREAD

**Issue by TimeSlinky** [DenizenScript/Depenizen#279]
Players can die and death messages will show but only after a player (TimeSlinky) has died, then the previous deaths will flood in chat. Example image below, Lksly was killed twice with no chat message, then TimeSlinky died and the death messages came in all at once?

Chat control give this in console not sure if it has anything to do with issue...:

```
30.09 19:28:52 [Server] INFO [19:28:52] [Server thread/INFO]: [ChatControl 8.3.4] Command event took 111.71 ms
30.09 19:28:52 [Server] INFO [19:28:52] [Server thread/INFO]: [ChatControl 8.3.4] Command Rules Check took 105.68 ms
30.09 19:28:52 [Server] INFO [19:28:52] [Server thread/INFO]: [ChatControl 8.3.4] Rules parse: commands.txt took 103.08 ms
```
![image](https://user-images.githubusercontent.com/10455839/65928621-a6a25200-e3cc-11e9-9316-c45444d1ef15.png)

Plugin list:
![image](https://user-images.githubusercontent.com/10455839/65928612-9ee2ad80-e3cc-11e9-87d9-58fe60e9a8c3.png)

**Comment by mcmonkey4eva** [comment]
I don't know what this issue is but I'm pretty confident it has nothing to do with Depenizen.

**Comment by TimeSlinky** [comment]
> I don't know what this issue is but I'm pretty confident it has nothing to do with Depenizen.

OOPS. Wrong github! haha mb
