### ISSUE TITLE
Cannot load Depenizen bridge for ...

### ISSUE THREAD

**Issue by Littledodger** [DenizenScript/Depenizen#281]
Hello,

I have issues with depenizen, when I start my server, I have the following error message :
> [22:33:27 INFO]: [Depenizen] Enabling Depenizen v2.0.0 (build 540)
> [22:33:27 INFO]: +> [Depenizen] Depenizen loading...
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'LuckPerms'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen loaded bridge for 'WorldEdit'!
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'AreaShop'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'TerrainControl'.
> [22:33:27 INFO]:  ERROR!
>      Error Message: Cannot load Depenizen bridge for 'Essentials': fundamental loading error:
>                    com/denizenscript/denizencore/tags/TagRunnable$RootForm
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PlaceholderAPI'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Towny'.
> [22:33:27 INFO]:  ERROR!
>      Error Message: Cannot load Depenizen bridge for 'Jobs': fundamental loading error:
>                    com/denizenscript/denizencore/tags/TagRunnable$RootForm
> [22:33:27 INFO]:  ERROR!
>      Error Message: Cannot load Depenizen bridge for 'MobArena': fundamental loading error:
>                    com/denizenscript/denizencore/tags/TagRunnable$RootForm
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PlotSquared'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Votifier'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PlayerPoints'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PVPArena'.
> [22:33:27 INFO]:  ERROR!
>      Error Message: Cannot load Depenizen bridge for 'WorldGuard': fundamental loading error:
>                    com/denizenscript/denizencore/tags/TagRunnable$RootForm
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'LibsDisguises'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'NoCheatPlus'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'OpenTerrainGenerator'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Sentinel'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'SkillAPI'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Factions'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'TownyChat'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'ASkyBlock'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Shopkeepers'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'MythicMobs'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Quests'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Residence'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'NoteBlockAPI'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'EffectLib'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PVPStats'.
> [22:33:27 INFO]:  ERROR!
>      Error Message: Cannot load Depenizen bridge for 'mcMMO': fundamental loading error:
>                    com/denizenscript/denizencore/tags/TagRunnable$RootForm
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'ViaVersion'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'BossShop'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Vampire'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen loaded bridge for 'GriefPrevention'!
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bridge for 'MagicSpells'.
> [22:33:27 INFO]: +> [Depenizen] Depenizen will not load bungee bridge.

Do you know why I have that ?

And when I stop the server, I Have an other error message : 

> [22:38:52 INFO]: [Depenizen] Disabling Depenizen v2.0.0 (build 540)
> [22:38:52 ERROR]: Error occurred while disabling Depenizen v2.0.0 (build 540) (Is it up to date?)
> java.lang.NoClassDefFoundError: com/denizenscript/denizencore/tags/TagRunnable$RootForm
>         at com.denizenscript.depenizen.bukkit.Depenizen.onDisable(Depenizen.java:53) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.4.jar:git-Paper-214]
>         at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.4.jar:git-Paper-214]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.14.4.jar:git-Paper-214]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439) ~[patched_1.14.4.jar:git-Paper-214]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432) ~[patched_1.14.4.jar:git-Paper-214]
>         at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:401) ~[patched_1.14.4.jar:git-Paper-214]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:733) ~[patched_1.14.4.jar:git-Paper-214]
>         at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:739) ~[patched_1.14.4.jar:git-Paper-214]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.14.4.jar:git-Paper-214]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
> Caused by: java.lang.ClassNotFoundException: com.denizenscript.denizencore.tags.TagRunnable$RootForm
>         at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-214]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-214]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
>         ... 11 more

Can somebody help me please ?

**Comment by Ph4i1ur3** [comment]
Update your Depenizen and Denizen together (you have a version mismatch)

**Comment by Littledodger** [comment]
Ok, my bad, there is a new version of denizen since yesterday...
thanks for help :)
