### ISSUE TITLE
Request for Bungee Tags

### ISSUE THREAD

**Issue by ChrispyMC** [DenizenScript/Depenizen#285]
If it is possible, can there be tags that lets scripters retrieve information about online players on a Bungee Proxy? A couple of requested tags are below.
`<bungee.list_players>` - lists every player on the Bungee Proxy
`<bungee.player_server[<PlayerTag>]>` - returns the Bungee connected server that the provided player tag is on,

**Comment by mcmonkey4eva** [comment]
Use the `BungeeTag` command and a bit of logic as-needed https://one.denizenscript.com/denizen/cmds/bungeetag
For more info ask on Discord at https://discord.gg/Q6pZGSR
