### ISSUE TITLE
some plugin login erro

### ISSUE THREAD

**Issue by bushuaichen** [DenizenScript/Depenizen#286]
[09:56:24 INFO]: [Depenizen] Enabling Depenizen v2.0.0 (build 559)
[09:56:24 INFO]: +> [Depenizen] Depenizen loading...
[09:56:24 INFO]:  ERROR!
     Error Message: Cannot load Depenizen bridge for 'LuckPerms': fundamental loading error:
[09:56:24 INFO]:  ERROR!
     Error Message: Internal exception was thrown!
[Error Continued] java.lang.NoClassDefFoundError: com/denizenscript/denizencore/tags/TagRunnable$RootForm
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.lambda$registerCoreBridges$9(Depenizen.java:107)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:71)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)
[Error Continued] Caused by: java.lang.ClassNotFoundException: com.denizenscript.denizencore.tags.TagRunnable$RootForm
[Error Continued] java.net.URLClassLoader.findClass(Unknown Source)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.lambda$registerCoreBridges$9(Depenizen.java:107)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:71)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)

[09:56:24 INFO]: +> [Depenizen] Depenizen loaded bridge for 'WorldEdit'!
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'AreaShop'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'TerrainControl'.
[09:56:24 INFO]:  ERROR!
     Error Message: Cannot load Depenizen bridge for 'Essentials': fundamental loading error:
[09:56:24 INFO]:  ERROR!
     Error Message: Internal exception was thrown!
[Error Continued] java.lang.NoClassDefFoundError: com/denizenscript/denizencore/tags/TagRunnable$RootForm
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.lambda$registerCoreBridges$4(Depenizen.java:102)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:71)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)
[Error Continued] Caused by: java.lang.ClassNotFoundException: com.denizenscript.denizencore.tags.TagRunnable$RootForm
[Error Continued] java.net.URLClassLoader.findClass(Unknown Source)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.lambda$registerCoreBridges$4(Depenizen.java:102)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:71)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)

[09:56:24 INFO]:  ERROR!
     Error Message: Cannot load Depenizen bridge for 'PlaceholderAPI': fundamental loading error:
[09:56:24 INFO]:  ERROR!
     Error Message: Internal exception was thrown!
[Error Continued] java.lang.NoClassDefFoundError: com/denizenscript/denizencore/tags/TagRunnable$RootForm
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.lambda$registerCoreBridges$17(Depenizen.java:115)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:71)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)
[Error Continued] Caused by: java.lang.ClassNotFoundException: com.denizenscript.denizencore.tags.TagRunnable$RootForm
[Error Continued] java.net.URLClassLoader.findClass(Unknown Source)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.lambda$registerCoreBridges$17(Depenizen.java:115)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:71)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)

[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Towny'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Jobs'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'MobArena'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PlotSquared'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Votifier'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PlayerPoints'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PVPArena'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'WorldGuard'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'LibsDisguises'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'NoCheatPlus'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'OpenTerrainGenerator'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Sentinel'.
[09:56:24 INFO]:  ERROR!
     Error Message: Cannot load Depenizen bridge for 'SkillAPI': Internal exception was thrown!
[09:56:24 INFO]:  ERROR!
     Error Message: Internal exception was thrown!
[Error Continued] java.lang.NoClassDefFoundError: com/denizenscript/denizen/utilities/implementation/BukkitScriptEntryData
[Error Continued] com.denizenscript.depenizen.bukkit.bridges.SkillAPIBridge.init(SkillAPIBridge.java:21)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:81)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)
[Error Continued] Caused by: java.lang.ClassNotFoundException: com.denizenscript.denizen.utilities.implementation.BukkitScriptEntryData
[Error Continued] java.net.URLClassLoader.findClass(Unknown Source)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] com.denizenscript.depenizen.bukkit.bridges.SkillAPIBridge.init(SkillAPIBridge.java:21)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:81)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)

[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Factions'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'TownyChat'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'ASkyBlock'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Shopkeepers'.
[09:56:24 INFO]:  ERROR!
     Error Message: Cannot load Depenizen bridge for 'MythicMobs': fundamental loading error:
[09:56:24 INFO]:  ERROR!
     Error Message: Internal exception was thrown!
[Error Continued] java.lang.NoClassDefFoundError: com/denizenscript/denizencore/tags/TagRunnable$RootForm
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.lambda$registerCoreBridges$13(Depenizen.java:111)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:71)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)
[Error Continued] Caused by: java.lang.ClassNotFoundException: com.denizenscript.denizencore.tags.TagRunnable$RootForm
[Error Continued] java.net.URLClassLoader.findClass(Unknown Source)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[Error Continued] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] java.lang.ClassLoader.loadClass(Unknown Source)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.lambda$registerCoreBridges$13(Depenizen.java:111)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:71)
[Error Continued] com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:32)
[Error Continued] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Error Continued] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[Error Continued] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[Error Continued] org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[Error Continued] net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[Error Continued] net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[Error Continued] java.lang.Thread.run(Unknown Source)

[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Quests'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Residence'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'NoteBlockAPI'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'EffectLib'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'PVPStats'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'mcMMO'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'ViaVersion'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'BossShop'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'Vampire'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'GriefPrevention'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bridge for 'MagicSpells'.
[09:56:24 INFO]: +> [Depenizen] Depenizen will not load bungee bridge.
[09:56:24 INFO]: +> [Depenizen] Depenizen loaded! 1 plugin bridge(s) loaded (of 35 available)

**Comment by mcmonkey4eva** [comment]
Update to the current Denizen dev build.
