### ISSUE TITLE
event "proxy server list ping" color issues

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Depenizen#290]
When using the event "on proxy server list ping", and trying to determine the MOTD, any color codes that are not at the start of the line cause the MOTD to stop displaying at that color code.
examples:
"<&b>Test<&c>Test" - will only show "<&b>Test" (with the color code parsed properly)
"Test<&c>Test" - will only show "Test"

Updated Depenizen, and Denizen (dev build) this morning after encountering issue. 
Bungeecord is latest version as well (build #1421)

**Comment by mcmonkey4eva** [comment]
This is pretty easy to replicate.
Seems to result from a mishandling in DepenizenBungee of Bungee's really weird text logic (it sometimes uses arrays and sometimes uses component objects that have arrays attached and ... asfsafsafsag)

**Comment by mcmonkey4eva** [comment]
Fixed via https://github.com/DenizenScript/DepenizenBungee/commit/8b4b97c3a2a368d9dc495801bd4d71c67f928455
