### ISSUE TITLE
MythicMob Bug

### ISSUE THREAD

**Issue by drAkeEngine** [DenizenScript/Depenizen#296]
Hello!

and found an error with the event "MythicMobDeathEvent"
Plugins:
Paper-237 (MC: 1.14.4)
Citizens v2.0.26-SNAPSHOT (build 1804)
Denizen v1.1.2-SNAPSHOT (build 1699-REL)
Depenizen v2.0.0 (build 587)
MythicMobs v4.9.0-SNAPSHOT-3085

I get this on the console

`07:47:06 a. m. [SEVERE] Could not pass event MythicMobDeathEvent to Denizen v1.1.2-SNAPSHOT (build 1699-REL)
07:47:06 a. m. java.lang.NoSuchMethodError: io.lumine.xikage.mythicmobs.api.bukkit.events.MythicMobDeathEvent.getMobLevel()I
07:47:06 a. m. 	at com.denizenscript.depenizen.bukkit.events.mythicmobs.MythicMobsDeathEvent.onMythicMobDeath(MythicMobsDeathEvent.java:175) ~[?:?]
07:47:06 a. m. 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor431.execute(Unknown Source) ~[?:?]
07:47:06 a. m. 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:442) ~[?:?]
07:47:06 a. m. 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor300.execute(Unknown Source) ~[?:?]
07:47:06 a. m. 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:750) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1419) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(EntityMonster.java:56) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityZombie.damageEntity(EntityZombie.java:284) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:411) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:240) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:212) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:370) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2286) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityMonster.tick(EntityMonster.java:37) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.EntityZombie.tick(EntityZombie.java:180) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:702) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:472) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-237]
07:47:06 a. m. 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
`

**Comment by mcmonkey4eva** [comment]
`MythicMobs v4.9.0-SNAPSHOT-3085`
No such version of MythicMobs exists. MythicMobs latest version is 4.7.2
The error originates from an incompatible version of MythicMobs. Please use the legitimate latest version, and not anything other than that.
