### ISSUE TITLE
MCMMO event issue

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Depenizen#299]
I am getting this error using the latest MCMMO 2.1.111, the latest depenizen 2.0.0 (build 590), and latest denizen release build 1700.
https://one.denizenscript.com/haste/63966

Here is the script I was using.
https://one.denizenscript.com/haste/63965

**Comment by mcmonkey4eva** [comment]
Latest McMMO supported is 2.0.0, they have not yet released any newer version than that.
