### ISSUE TITLE
SkillAPI Integration -- using skill_level Tag

### ISSUE THREAD

**Issue by sirbandersnatch** [DenizenScript/Depenizen#300]
https://one.denizenscript.com/paste/63995

I am trying to get access to the skill level of a SkillAPI skill.  
<player.skillapi.skill_level[Perception]> throws some errors. Please advise.

**Comment by mcmonkey4eva** [comment]
You don't have SkillAPI on your server in the first place.

**Comment by sirbandersnatch** [comment]
Just to humor me, can you let me know if the skill_level Tag still works? And if so, if I used it in the correct way?

**Comment by mcmonkey4eva** [comment]
Your narrate lines were fine.
Your if line was wrong.
Your usage is `{ braces }` is outdated legacy code
https://guide.denizenscript.com/guides/this-guide/updates-since-videos.html#colon-syntax

The actual problem you encountered is that you literally don't have SkillAPI installed.
