### ISSUE TITLE
MMOCORE Support?

### ISSUE THREAD

**Issue by drAkeEngine** [DenizenScript/Depenizen#303]
Hello good afternoon.

This plugin is premium (paid), I do not know that is adapted to the laws or restrictions of the Minecraft EULA, and tried to investigate about what can be done or not with the complements and how the EULA applies, through Spigot that apparently It has a MIT type license and I don't know if that's why plugins such as: "MCMMO, Mythicmobs" among other popular ones are distributed in premiumversions.

Since Spigot proposes that to have a payment plugin you need minimum requirements within the community to be able to distribute such an pligin

I explain this because I know very little about laws and I don't want to offend the team, I know they are serious developers and I really don't want to cause controversy.

Personally, looking for plugins for my server that I have been developing for a long time, I found this plugin that has very nice benefits for my server.

And I want to adapt it together with the Denizens

the flags would be very similar to those currently found with SKillApi as well as events, information about classes, professions, leveling up events etc.

In advance, thank you very much for your time and an apology for my bad English and for the little knowledge about EULA.

**Comment by gominecraft** [comment]
Depenizen already hooks into MM. I see no inherent reason you can't use the exposed APIs in MMOCore/MMOLib within Depenizen as well. Someone just has to do the work.

I would recommend the following, if you aren't hip on development yourself:

Write up a use-case that exposes the (hopefully) myriad of possible benefits hooking into MMOCore/MMOLib will offer.

**Comment by drAkeEngine** [comment]
Well, basically do scripts that support missions, objectives and interfaces for players.

check the level of a player's class to access some dungeon <player.flag[mmocore.player.profession[miner].level]>

Or that an npc requires a certain level of the player's class in order to interact:
- if <player.flag[mmocore.player.mainclass.level> == x

or maybe an ability within your skill tree at a certain level that allows access to an area
- if <player.flag[mmocore.player.has_skill[fireboom]> && <player.flag[mmocore.player.skill[fireboom].level> => 10

**Comment by mcmonkey4eva** [comment]
We can not, will not, and will never, support Premium-only plugins via Depenizen, for technical, moral, and legal reasons.

I note that premium-only is indeed an explicit violation of the Minecraft EULA.

Spigot itself is possibly in violation of the Minecraft EULA and very likely in violation of the intellectual property of former Bukkit developers, however they intentionally host their servers in places like Romania (a country not subject to most international laws) to skirt past those laws.
