### ISSUE TITLE
Additional magicspells support

### ISSUE THREAD

**Issue by Baileyc889** [DenizenScript/Depenizen#304]
I would like to request a few additional things for depenizen-magicspells.

Could a tag be made for a players max mana?
<playertag.magicspells.max_mana>

Could a mechanism also be made to adjust both a players mana and max mana as well?

**Comment by mcmonkey4eva** [comment]
Is there any reason you wouldn't be able to make the mana changes via `- execute`?

**Comment by mcmonkey4eva** [comment]
The `max_mana` tag is added. If it's not possible to `- execute` the changes, we can reopen the issue and look into mechanisms for those.
