### ISSUE TITLE
Placeholder API Bridge Potentially Broken

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Depenizen#307]
%denizen_<tag>% placeholders might be broken by some of the latest core changes. My assumption is Depenizen handles these.

No idea if this is an issue, also note the user is on 1.12.2 and in offline mode. But sounds like it could in theory be an issue regardless of that. Haven't looked too far into it, especially since they're on an old version and in offline mode, so posting this issue.

Logs they provided - https://gist.github.com/bushuaichen/c77c59d33167015861dcbef9f9e0754c
Discord context - https://discordapp.com/channels/315163488085475337/315163488085475337/674429492990574616

**Comment by bushuaichen** [comment]
I've removed the other plug-ins. There are only a few left:
https://gist.github.com/bushuaichen/b46a65a4b18e31f7f3ebc329306db783

**Comment by mcmonkey4eva** [comment]
Please do not post github issues related to in-progress core update. As was stated in the changelogs, the update CAN and WILL break things.
