### ISSUE TITLE
MythicMobs Mechanic

### ISSUE THREAD

**Issue by quochungudon** [DenizenScript/Depenizen#308]
Can you add more mechanics for mythicmobs ? Like mob score , mob level , mob threat 

Here is some link:
https://www.mythicmobs.net/manual/doku.php/databases/mobs/levels
https://www.mythicmobs.net/manual/doku.php/databases/mobs/modules/threattables

**Comment by mcmonkey4eva** [comment]
Looks to be a duplicate of #260
