### ISSUE TITLE
Add WorldBorder Support

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#309]
I am looking for some way to pregenerate chunks 

This plugin have a feature for that:
https://www.spigotmc.org/resources/worldborder.60905/
Mainly looking for command or mechanism to WorldFillTask:
https://github.com/Brettflan/WorldBorder/blob/master/src/main/java/com/wimbli/WorldBorder/WorldFillTask.java

This might also help with the chunkload issue from https://github.com/DenizenScript/Denizen/issues/1951 
and maybe the regenerate mechanism issue https://one.denizenscript.com/denizen/mecs/regenerate

**Comment by mcmonkey4eva** [comment]
This is literally just a glorified `chunkload` command in a loop. Replicate it with a script, there's no need for plugin interop for that.

**Comment by mcmonkey4eva** [comment]
Also, the issue you linked is closed for a reason... it's been resolved.
