### ISSUE TITLE
WorldEdit & FAWE is throwing java error

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Depenizen#315]
Hi, maybe just only WorldEdit is supported, but if it the case I should not receive this error when I have FAWE on my server ?

Server version : git-Paper-149 (MC: 1.15.2)
Depenizen version : 2.0.0 (build 611)
FAWE version : FastAsyncWorldEdit-1.15#157
Haste : https://one.denizenscript.com/haste/66719
Full server log : https://one.denizenscript.com/haste/66720

**Comment by SXRWahrheit** [comment]
Pursuant to the plugin list you were *just* given on Discord, Depenizen supports WorldEdit, not FastAsyncWorldEdit.

**Comment by Noiknez** [comment]
I saw the list after posting this. Event is FAWE is not supported, Depenizen shouldn't trow any error right ?

**Comment by Noiknez** [comment]
The error is also appearing for Worldedit 7.0.2 https://one.denizenscript.com/haste/66721

**Comment by mergu** [comment]
This is an error because Depenizen is pointing at code that's not in the release builds of Denizen yet. Use the latest Denizen Dev build: https://ci.citizensnpcs.co/job/Denizen_Developmental/

**Comment by Noiknez** [comment]
Thank you @mergu it work now

**Comment by mergu** [comment]
No problem. You can close the issue
