### ISSUE TITLE
Quality Armor and Crackshot expansion 

### ISSUE THREAD

**Issue by cowbilet** [DenizenScript/Depenizen#317]
Events: 
on player shoots with <gun>
on player aims with <gun>
on player reload with <gun>
Tags: 
<entity.is_shooting> 
<entity.is_aiming>
<item.ammo>
<item.is_empty>
<entity.is_reloading>
Mech:
ammo (adjusts ammo on a gun)
Example: /ex adjust <player.item_in_hand> ammo:30

**Comment by Fortifier42** [comment]
What is `Quality Armor`
