### ISSUE TITLE
McMMO seems to be overriding scripts

### ISSUE THREAD

**Issue by BBCSS** [DenizenScript/Depenizen#319]
Ever since updating plugins the other day, McMMO overrides scripts I write for breaking blocks and whatnot. Every few blocks will drop the vanilla item instead of any scripted item. When I have the appropriate perms, I gain McMMO xp each time it happens, but it happens to people even without the perms/XP gain. I reverted back to old McMMO versions before this was happening, but it persists. This leads me to suspect it might have actually been a change in Depenizen.

Paper-298
Depenizen-618
Denizen-1708

**Comment by mcmonkey4eva** [comment]
Ask for basic help on Discord @ https://discord.gg/Q6pZGSR
