### ISSUE TITLE
PlotSquared v5 not compatible

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Depenizen#324]
Logs:
https://one.denizenscript.com/haste/70661#124

**Comment by Mwthorn** [comment]
It should also be noted that PlotSquared builds are now behind a pay-wall but it is still possible to compile the source code.

**Comment by mcmonkey4eva** [comment]
If/when they publicly post an official v5 jar, we will add compatibility for it. Until such time, we can't/won't.
