### ISSUE TITLE
[MythicMobs] events no work 

### ISSUE THREAD

**Issue by drAkeEngine** [DenizenScript/Depenizen#326]
hello, could you add Depenizen support for mythicmobs 4.9.1?

the event on mythicmob mob dies
It doesn't work, I am using

Spigot 1.15.2 
Depenizen-2.0.0-b631
Mythicmobs 4.9.1

thank you very much and good night

**Comment by mcmonkey4eva** [comment]
Depenizen already targets mm 4.9.1 for support.

If you're encountering issues, please ping me on Discord with a debug log.
