### ISSUE TITLE
<player.job[<job_name>].xp> should return 0 if the player does not have this job

### ISSUE THREAD

**Issue by Tolmikarc** [DenizenScript/Depenizen#328]
I am currently trying to write a script to transfer over players current jobs xp from all of their jobs and move it to one new job. In doing so I am having to use the .add tag to add together their current xp. The issue is that if the player is not a member of the job that is listed first in the list of jobs xp to add, the tag is not parsed. 

For example, if I am adding up the xp of Miner and Farmer job and I use <player.job[Miner].xp.add[<player.job[Farmer].xp>]> and the player is only a member of the miner job, it will spit out whatever xp they have in the miner job. If I use that same tag though and they are only a member of the farmer job, it spits out the tag and does not parse. 

If either making this possible to do without error or adding an entirely new tag for total xp earned across all jobs, that would be greatly appreciated.

**Comment by Fortifier42** [comment]
If the player does not have the job they do not have `0` XP for it. Use a fallback for this. The idea is that you check if the player has the Job before retrieving the XP.

**Comment by mcmonkey4eva** [comment]
https://one.denizenscript.com/denizen/lngs/fallback
