### ISSUE TITLE
New tag for skillapiskill tag

### ISSUE THREAD

**Issue by khanhtung74** [DenizenScript/Depenizen#329]
Can you add new tag for the method [Skill#getIndicator()](http://eniripsa96.github.io/SkillAPI/javadoc/#getIndicator7?400:0;com.sucy.skill.api.skills:Skill) return itemtag similar to <SkillAPIClassTag.icon> ?

**Comment by mcmonkey4eva** [comment]
Added to new builds as `<PlayerTag.skillapi.skill_indicator[<skill>]>`
