### ISSUE TITLE
WorldGuard Events

### ISSUE THREAD

**Issue by drAkeEngine** [DenizenScript/Depenizen#336]
Is it possible to add an event that supports when a player enters a region of the worldguard plugin? 😁

**Comment by mcmonkey4eva** [comment]
Why not just use a cuboid, with the enters area event?

**Comment by drAkeEngine** [comment]
Hi, thanks for your time

It is how I have it at the moment, but there are regions on my server that are created in the shape of a polygon and it is very difficult to create the areas with the cuboids so that the events are executed correctly.

That is why I dare to ask for support for the worldguard regions, this would give more versatility when creating areas and executing events

I'm sorry if my english is bad 😥

**Comment by mcmonkey4eva** [comment]
PolygonTags exist in Denizen now, so this issue is irrelevant
