### ISSUE TITLE
Understanding of a method in src/main/java/com/denizenscript/depenizen/bukkit/utilities/mythicmobs/conditions/DenizenCondition.java

### ISSUE THREAD

**Issue by 129124** [DenizenScript/Depenizen#339]
Hi there, when I was reading the code of the function "public boolean check(AbstractEntity entity)" in src/main/java/com/denizenscript/depenizen/bukkit/utilities/mythicmobs/conditions/DenizenCondition.java, I found it has no Javadoc. My understanding is “check if   the current oauth2 authentication has already been granted @param entity the   entity from which to check for the target object   @return true if the new false otherwise". Can you please check if this is correct? Thanks.

**Comment by Fortifier42** [comment]
Support is on Discord: https://discord.gg/Q6pZGSR

**Comment by 129124** [comment]
Thanks.
