### ISSUE TITLE
Mythicskill of Mythicmobs

### ISSUE THREAD

**Issue by Yyexu** [DenizenScript/Depenizen#340]
Why can't depenizen-2.0.0-b613 use mythickill?Denizen indicates that the command is wrong.But I want use Mythicskill command,What version should I use ? MC version is 1.12.2, The version of denizen is 1.13 b1704-REL.What should I do? Could you tell me, please.Thx XD

**Comment by Fortifier42** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
