### ISSUE TITLE
Sentinel HealRate does not fire `on entity heals` event

### ISSUE THREAD

**Issue by evelyn-f-king** [DenizenScript/Depenizen#345]
Setting a Sentinel's healing rate with `/sentinel healrate` does not fire the `on entity heals` event. Tested with the following:
```
MainDamageEvent:
  type: world
  debug: false
  events:
    on npc heals:
    - announce "Healed! "
```
Version screenshots below:
![image](https://user-images.githubusercontent.com/62361990/93385748-83f68c80-f81b-11ea-92fc-1a4bc9adf04d.png)
![image](https://user-images.githubusercontent.com/62361990/93385769-8bb63100-f81b-11ea-96d0-7ce76cb34a40.png)
![image](https://user-images.githubusercontent.com/62361990/93385804-95d82f80-f81b-11ea-84d5-a0fcc7b371b2.png)

Throwing splash potions at the NPC does heal it and fire the event, so I know I can at least trigger the event that way.

**Comment by mcmonkey4eva** [comment]
This should be posted as a Sentinel issue, as I mentioned on Discord.
