### ISSUE TITLE
Events in MythicMobs v4.11.0-BETA don't work

### ISSUE THREAD

**Issue by drAkeEngine** [DenizenScript/Depenizen#352]
Hello, I am currently using this version of the mythicmobs plugin in its free version, but I cannot make the events work, I would like to know if there is still compatibility with this plugin.

Thank you very much for your excellent work.
and excuse me if my english is bad

**Comment by mcmonkey4eva** [comment]
basic support is on Discord @ https://discord.gg/Q6pZGSR
