### ISSUE TITLE
Saber Factions Support

### ISSUE THREAD

**Issue by thepagon** [DenizenScript/Depenizen#364]
Please add support for SaberFactions in Depenizen!!! It's a very popular plugin and it would just use the same tags as the other factions plugins, so that you can get the name of a players faction with a tag, or just everything that depenizen already supports with the other faction plugin. (But the name is the most important for me so that you can replace chat plugins with denizen)

**Comment by mcmonkey4eva** [comment]
The following is the `plugin.yml` for saber factions:
```
name: Factions
version: 1.6.9.5-2.6.8-STABLE
api-version: 1.13
main: com.massivecraft.factions.FactionsPlugin
```

It is identifying itself as `Factions`, and using the same package as the official Factions. If it is API-Compatible with the official factions plugin, it is supported in Depenizen the same as official Factions. If it is not API-Compatible, that cannot be resolved from Depenizen's end and is up to them to resolve themselves (they can either change the plugin & package names, or guarantee API compatibility with the upstream Factions).
