### ISSUE TITLE
Error when starting server causing by the 3rd party plugin is the same name

### ISSUE THREAD

**Issue by ArtifactyNight** [DenizenScript/Depenizen#367]
Error: https://mcpaste.io/d7b1ef95323ed037

I use this "Quest" plugin to make quest (this plugin i'm used not support with Depenizen)
https://www.spigotmc.org/resources/quests-1-8-1-17-set-up-goals-for-players.23696/

but this "Quests" plugin is supported
https://www.spigotmc.org/resources/quests.3711/

so.. both plugins is the same name ("Quests" and "Quests")
maybe it's error because of this?

**Comment by mcmonkey4eva** [comment]
Yep, that'll happen. The errors shouldn't actually break anything, just yell in your console because of the name conflict.

Both plugins have *terrible* names. Wish the developers would think to name their plugins something remotely unique.
