### ISSUE TITLE
mobarena arena wave changes is not matched to any ScriptEvents

### ISSUE THREAD

**Issue by BBCSS** [DenizenScript/Depenizen#368]
Not sure if they made some changes on their end or what but I haven't been able to get it to fire.

Error Message: Event MOBARENA_HANDLERS.events.on mobarena arena wave changes is not matched to any ScriptEvents.

**Comment by mcmonkey4eva** [comment]
Bug reports go on Discord @ https://discord.gg/Q6pZGSR
