### ISSUE TITLE
Error Message: Unable to register property 'EssentialsPlayerProperties'! 

### ISSUE THREAD

**Issue by Tarlak333** [DenizenScript/Depenizen#376]
Latest Purpur 1.18.2, EssentialsX Latest Dev Build 2.20.0-dev+5-d891268

Depenizen Startup Error:
https://pastebin.com/AM6KCwaH

Full Startup Log:
https://controlc.com/102e3b73

**Comment by mcmonkey4eva** [comment]
support is on Discord @ https://discord.gg/Q6pZGSR
