### ISSUE TITLE
SimpleClans support

### ISSUE THREAD

**Issue by Tomut0** [DenizenScript/Depenizen#377]
Hello there, I'm a collaborator of SimpleClans and want to see the linking between these nice plugins.
In a few words, SimpleClans is like Factions, but with more nice features and long support.

We're using these general definitions:
* **ClanPlayer** is a class that represents a player object. 
This class contains information about the player, his clan, etc.
* **Clan** is a class that presents a clan object. 
It has methods for getting clan players, clan tag, allies, leaders, etc.
* **ClanManager** is a class that allows you to retrieve Clan and ClanPlayer.

We have a lot of feature requests, which really sounds like individual for each server.
Yes, we have the API, but learning Denizen is much simpler than Java, right? 🍵  

The tags will look the similar as Factions:
- <clan[tag]> - Returns ClanTag.
- <clans.list> - Returns all clans on the server.
- <PlayerTag.clan> - Returns the player's clan (it's null if player is not a member of clan).
- etc.

The couple of difference with Factions that you must know:
 - We don't have our claim system, we provide to existing ones.
 - We don't have power system.
 
Also, if I'll make a PR for adding that support, would you be fine with it?
 
[Javadoc](https://ci.roinujnosde.me/job/SimpleClans/Javadoc/) [Wiki](https://wiki.roinujnosde.me/simpleclans/) [Spigot](https://www.spigotmc.org/resources/simpleclans.71242/)

**Comment by BehrRiley** [comment]
We typically look forward to discussing PR's in our discord before initiating them: https://discord.gg/Q6pZGSR

However, creating a bridge for another plugin to be used with Denizen is handled with Depenizen: https://github.com/DenizenScript/Depenizen

We always love contributions though, absolutely

**Comment by Tomut0** [comment]
> We typically look forward to discussing PR's in our discord before initiating them

I marked there as `DoNotSupport`. 😃 
But it was fair, so I have no complaints.
