### ISSUE TITLE
Getting log errors on server startup

### ISSUE THREAD

**Issue by DrakorthaP** [DenizenScript/Depenizen#398]
hello, I was hoping I could get some help with these errors. doesnt anyone know a solution? thank you

https://pastebin.com/kinSZyDy

**Comment by tal5** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR

**Comment by DrakorthaP** [comment]
I don't have discord :/

**Comment by mcmonkey4eva** [comment]
Well, click the invite link and create an account. it's free and simple. You don't even need the app you can use it entirely as a website.
