### ISSUE TITLE
Problems with WorldGuard version 1.21

### ISSUE THREAD

**Issue by Boddebon** [DenizenScript/Depenizen#433]
Plugin version: 2.1.0 (build 863)

Kernel version: purpur-1.21-2260

WorldGuard Version: 7.0.11 Beta 1

Description: When you turn on the server, it gives an error.

Error: 
[21:00:37 INFO]: +> [Depenizen] Loaded bridge for 'PlaceholderAPI'! 
[21:00:37 INFO]:  ERROR!
                 Error Message: Cannot load Depenizen bridge for 'WorldGuard': Internal exception was thrown! 
[21:00:37 INFO]: Additional Error Info: Internal exception was thrown!
[Error Continued] java.lang.NoClassDefFoundError: net/citizensnpcs/api/util/DataKey
[Error Continued]   Depenizen-2.1.0-b863.jar//com.denizenscript.depenizen.bukkit.properties.worldguard.WorldGuardNPCExtensions.register(WorldGuardNPCExtensions.java:22)
[Error Continued]   Depenizen-2.1.0-b863.jar//com.denizenscript.depenizen.bukkit.bridges.WorldGuardBridge.init(WorldGuardBridge.java:36)
[Error Continued]   Depenizen-2.1.0-b863.jar//com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:90)
[Error Continued]   Depenizen-2.1.0-b863.jar//com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:35)
[Error Continued]   org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[Error Continued]   io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[Error Continued]   io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[Error Continued]   org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[Error Continued]   org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643)
[Error Continued]   org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592)
[Error Continued]   net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:756)
[Error Continued]   net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:518)
[Error Continued]   net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361)
[Error Continued]   net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234)
[Error Continued]   net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[Error Continued]   java.base/java.lang.Thread.run(Thread.java:1583)
[Error Continued] Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.util.DataKey
[Error Continued]   org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[Error Continued]   org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[Error Continued]   java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[Error Continued]   Depenizen-2.1.0-b863.jar//com.denizenscript.depenizen.bukkit.properties.worldguard.WorldGuardNPCExtensions.register(WorldGuardNPCExtensions.java:22)
[Error Continued]   Depenizen-2.1.0-b863.jar//com.denizenscript.depenizen.bukkit.bridges.WorldGuardBridge.init(WorldGuardBridge.java:36)
[Error Continued]   Depenizen-2.1.0-b863.jar//com.denizenscript.depenizen.bukkit.Depenizen.loadBridge(Depenizen.java:90)
[Error Continued]   Depenizen-2.1.0-b863.jar//com.denizenscript.depenizen.bukkit.Depenizen.onEnable(Depenizen.java:35)
[Error Continued]   org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[Error Continued]   io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[Error Continued]   io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[Error Continued]   org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[Error Continued]   org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643)
[Error Continued]   org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592)
[Error Continued]   net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:756)
[Error Continued]   net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:518)
[Error Continued]   net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361)
[Error Continued]   net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234)
[Error Continued]   net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[Error Continued]   java.base/java.lang.Thread.run(Thread.java:1583)

[21:00:37 INFO]: +> [Depenizen] Depenizen loaded! 4 plugin bridge(s) loaded (of 42 available)

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR in the `denizen` channel
