### ISSUE TITLE
Multiple plugins support request

### ISSUE THREAD

**Issue by PSYCHEER** [DenizenScript/Depenizen#435]
Hey there! I want to ask if could be possible to add a support for all plugins made by Auxilor, I mean Eco-plugins
Why?
I'm using his whole suite on my server and I'm actively using Denizen as well and I will be too excited if I can integrate these plugins together on internal way instead of commanded way

Next plugin
GriefDefender
I know Depenizen has support for GriefPrevention, which is nice, but as I'm using Defender, which is paid and really integrated into server core, is hard to switch even in the way of my feelings.

Could be this possible? Thanks in advance.

**Comment by mcmonkey4eva** [comment]
One request per post, and link the relevant plugin, provide specifics about what you want and why.

Note that premium plugins cannot be supported.
